function getCoins() {
  return coinsData;
}

let coinsData = [
  {
    amount: 110802.33,
    coingecko: "ripple",
    id: 4,
    imageUrl: "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
    symbol: "XRP",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 1.8056,
    coingecko: "ethereum",
    id: 5,
    imageUrl:
      "https://assets.coingecko.com/coins/images/279/small/ethereum.png",
    symbol: "ETH",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 0.111,
    coingecko: "bitcoin",
    id: 6,
    imageUrl: "https://assets.coingecko.com/coins/images/1/small/bitcoin.png",
    symbol: "BTC",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 1025.275,
    coingecko: "energy-web-token",
    id: 7,
    imageUrl:
      "https://www.energyweb.org/wp-content/uploads/2022/11/cropped-ew-favicon-192x192.png",
    symbol: "EWT",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 257,
    coingecko: "polkadot",
    id: 8,
    imageUrl:
      "https://assets.coingecko.com/coins/images/12171/small/polkadot.png",
    symbol: "DOT",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 360,
    coingecko: "chainlink",
    id: 9,
    imageUrl:
      "https://assets.coingecko.com/coins/images/877/small/chainlink-new-logo.png",
    symbol: "LINK",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 4533.2454,
    coingecko: "matic-network",
    id: 10,
    imageUrl:
      "https://assets.coingecko.com/coins/images/4713/small/matic-token-icon.png",
    symbol: "matic",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 32500.908,
    coingecko: "stellar",
    id: 11,
    imageUrl:
      "https://assets.coingecko.com/coins/images/100/small/Stellar_symbol_black_RGB.png",
    symbol: "XLM",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 5000,
    coingecko: "algorand",
    id: 12,
    imageUrl: "https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png",
    symbol: "ALGO",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 0,
    coingecko: "uniswap",
    id: 13,
    imageUrl:
      "https://assets.coingecko.com/coins/images/12504/small/uniswap-uni.png",
    symbol: "UNI",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 7.1,
    coingecko: "monero",
    id: 14,
    imageUrl:
      "https://assets.coingecko.com/coins/images/69/small/monero_logo.png",
    symbol: "XMR",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 4511.43,
    coingecko: "solo-coin",
    id: 15,
    imageUrl: "https://assets.coingecko.com/coins/images/10771/small/solo.png",
    symbol: "SOLO",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 0,
    coingecko: "xi-token",
    id: 16,
    imageUrl: "https://etherscan.io/token/images/xiprotocol_32.png",
    symbol: "XI",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 51.373687392,
    coingecko: "klima-dao",
    id: 17,
    imageUrl: "https://polygonscan.com/token/images/klimadao_32.png",
    symbol: "KLIMADao",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 280.117167,
    coingecko: "cosmos",
    id: 18,
    imageUrl:
      "https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png",
    symbol: "ATOM",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 131226.3932,
    coingecko: "hedera-hashgraph",
    id: 19,
    imageUrl: "https://hedera.com/assets/images/black-whiteH-192x192.png",
    symbol: "HBAR",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 33.3,
    coingecko: "mobilecoin",
    id: 20,
    imageUrl:
      "https://assets.coingecko.com/coins/images/13311/small/mobilecoin.png",
    symbol: "MOB",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 1276.1,
    coingecko: "coreum",
    id: 21,
    imageUrl:
      "https://assets.coingecko.com/coins/images/24169/small/2b7Phdmz_400x400.png",
    symbol: "CORE",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 0,
    coingecko: "dash",
    id: 22,
    imageUrl:
      "https://assets.coingecko.com/coins/images/19/small/dash-logo.png",
    symbol: "DASH",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 300000,
    coingecko: "verasity",
    id: 24,
    imageUrl: "https://etherscan.io/token/images/verasity_32.png",
    symbol: "VRA",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 13000,
    coingecko: "xdce-crowd-sale",
    id: 25,
    imageUrl: "https://www.xinfin.io/assets/images/brand-assets/xdc-icon.png",
    symbol: "XDC",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 150000,
    coingecko: "digibyte",
    id: 26,
    imageUrl: "https://assets.coingecko.com/coins/images/63/small/digibyte.png",
    symbol: "DGB",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 127.5,
    coingecko: "injective-protocol",
    id: 27,
    imageUrl:
      "https://assets.coingecko.com/coins/images/12882/small/Secondary_Symbol.png",
    symbol: "INJ",
    priceValue: 0,
    priceCalcValue: 0,
  },
  {
    amount: 20,
    coingecko: "gmx",
    id: 28,
    imageUrl: "https://assets.coingecko.com/coins/images/18323/small/arbit.png",
    symbol: "GMX",
  },
];
